<?php

namespace Container5rw1k1q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPersonnage2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.cCMS14h.App\Entity\Personnage' shared service.
     *
     * @return \App\Entity\Personnage
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.cCMS14h": it needs an instance of "App\\Entity\\Personnage" but this type has been excluded in "config/services.yaml".');
    }
}
