<?php

namespace ContainerWDGNisE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TslnHH5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TslnHH5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TslnHH5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\PersonnageController::index' => ['privates', '.service_locator.1JTT3Xa.App\\Controller\\PersonnageController::index()', 'getPersonnageControllerindexService', true],
            'App\\Controller\\PersonnageController::new' => ['privates', '.service_locator.LNc4qC2.App\\Controller\\PersonnageController::new()', 'getPersonnageControllernewService', true],
            'App\\Controller\\PersonnageController::show' => ['privates', '.service_locator.cCMS14h.App\\Controller\\PersonnageController::show()', 'getPersonnageControllershowService', true],
            'App\\Controller\\PersonnageController::edit' => ['privates', '.service_locator.YCwKpwg.App\\Controller\\PersonnageController::edit()', 'getPersonnageControllereditService', true],
            'App\\Controller\\PersonnageController::delete' => ['privates', '.service_locator.YCwKpwg.App\\Controller\\PersonnageController::delete()', 'getPersonnageControllerdeleteService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.tEL1pRK.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\UserController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\UserController::login()', 'getUserControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\PersonnageController:index' => ['privates', '.service_locator.1JTT3Xa.App\\Controller\\PersonnageController::index()', 'getPersonnageControllerindexService', true],
            'App\\Controller\\PersonnageController:new' => ['privates', '.service_locator.LNc4qC2.App\\Controller\\PersonnageController::new()', 'getPersonnageControllernewService', true],
            'App\\Controller\\PersonnageController:show' => ['privates', '.service_locator.cCMS14h.App\\Controller\\PersonnageController::show()', 'getPersonnageControllershowService', true],
            'App\\Controller\\PersonnageController:edit' => ['privates', '.service_locator.YCwKpwg.App\\Controller\\PersonnageController::edit()', 'getPersonnageControllereditService', true],
            'App\\Controller\\PersonnageController:delete' => ['privates', '.service_locator.YCwKpwg.App\\Controller\\PersonnageController::delete()', 'getPersonnageControllerdeleteService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.tEL1pRK.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\UserController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\UserController::login()', 'getUserControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\PersonnageController::index' => '?',
            'App\\Controller\\PersonnageController::new' => '?',
            'App\\Controller\\PersonnageController::show' => '?',
            'App\\Controller\\PersonnageController::edit' => '?',
            'App\\Controller\\PersonnageController::delete' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\UserController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\PersonnageController:index' => '?',
            'App\\Controller\\PersonnageController:new' => '?',
            'App\\Controller\\PersonnageController:show' => '?',
            'App\\Controller\\PersonnageController:edit' => '?',
            'App\\Controller\\PersonnageController:delete' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\UserController:login' => '?',
        ]);
    }
}
