<?php

namespace ContainerWDGNisE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPersonnageControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cCMS14h.App\Controller\PersonnageController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cCMS14h.App\\Controller\\PersonnageController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'personnage' => ['privates', '.errored..service_locator.cCMS14h.App\\Entity\\Personnage', NULL, 'Cannot autowire service ".service_locator.cCMS14h": it needs an instance of "App\\Entity\\Personnage" but this type has been excluded in "config/services.yaml".'],
        ], [
            'personnage' => 'App\\Entity\\Personnage',
        ]))->withContext('App\\Controller\\PersonnageController::show()', $container);
    }
}
