<?php

namespace ContainerWDGNisE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPersonnageControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YCwKpwg.App\Controller\PersonnageController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YCwKpwg.App\\Controller\\PersonnageController::delete()'] = ($container->privates['.service_locator.YCwKpwg'] ?? $container->load('get_ServiceLocator_YCwKpwgService'))->withContext('App\\Controller\\PersonnageController::delete()', $container);
    }
}
