<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTxVUtx8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTxVUtx8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTxVUtx8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTxVUtx8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTxVUtx8\App_KernelDevDebugContainer([
    'container.build_hash' => 'TxVUtx8',
    'container.build_id' => 'b509e4e4',
    'container.build_time' => 1739194109,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTxVUtx8');
